version: '3.5'

services:
  api:
    build: ./server
    # ports:
    #   - '5000:5000'
    command: 'npm start'
  web:
    build: ./web
    # ports:
    #   - '80:80'
    # depends_on:
    #   - api
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - web
      - api